version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6   # Specify the .NET SDK version you are using
    commands:
      # Optionally, update the .NET SDK
      - echo Installing .NET Core SDK...
  
  pre_build:
    commands:
      - echo Restoring dependencies...
      - dotnet restore

  build:
    commands:
      - echo Building the project...
      - dotnet build MyProject.sln --configuration Release

  post_build:
    commands:
      - echo Running unit tests...
      - dotnet test MyProject.Tests/MyProject.Tests.csproj --configuration Release --no-build --verbosity normal

      - echo Publishing the application...
      - dotnet publish MyProject/MyProject.csproj --configuration Release --output ./publish

artifacts:
  files:
    - '**/*'
  base-directory: './publish'  # This tells AWS to use the published output as the artifact for deployment
